### ISSUE TITLE
Consider using web scraping

### ISSUE THREAD

**Issue by JuanjoSalvador** [Kylart/Nyaapi#1]
You are getting only 75 results, because you're using the RSS version of the result page. Consider using the HTML version and Cheerio or something like it for parsing the web and get the torrents info.

This allows you to make requests using the page filter and a lot of more cool features.

**Comment by Kylart** [comment]
You are absolutely right! I've been thinking about it lately.
 
I am kinda busy with some other projects I must work on. Be sure it's gonna happen though!

**Comment by JuanjoSalvador** [comment]
I have my own version of Nyaa "API" built with Python and web scraping, I guess I could build something similar using NodeJS.

Btw, NyaaPantsu has its own API now, we can use it instead of scraping or RSS page.

**Comment by Kylart** [comment]
Oh you're actually right!
 
I'll probably do some upgrade by monday then.

**Comment by Kylart** [comment]
This is solved in 2.0.0 (To be merged soon)
