### ISSUE TITLE
Can't get uploads from User with 'searchAllByUser'

### ISSUE THREAD

**Issue by Zhoosher** [Kylart/Nyaapi#15]
So i am trying to get all the uploads from a user but it always errors out. It seems to be a 404 error that happens while requesting a page which doesnt exist (the user doesn't have more than 1000 uploads).

The code i am using:

`const nyaaSearchByUser = await si.searchAllByUser('Moozzi2');`

The error that i get in full is https://paste.ee/p/lKwjx.

I tried to bypass the error here in that specific case by searching for the uploaders tag [Moozzi2], which did return his uploads but i saw that there is no possibility to check the uploader in the returned object (maybe an idea to add that).

**Comment by Kylart** [comment]
I just released version 2.3.1 which contains the fix for this.
