### ISSUE TITLE
Using NyaaPantsu API

### ISSUE THREAD

**Issue by JuanjoSalvador** [Kylart/Nyaapi#2]
Consider using NyaaPantsu API instead of web scraping/RSS scraping.

I wrote a JS module for this purpose, allows you to search torrents and view single torrent. It's MIT licensed, so you can use it if you want for Nyaapi.

https://www.npmjs.com/package/pantsu-js

Cheers.

**Comment by Kylart** [comment]
I am currently writing methods allowing one to fully use the nyaa pantsu API. No worries 😄 
Expect 2.0.0 to come along with #1 about next week!

**Comment by JuanjoSalvador** [comment]
Cool :)

**Comment by Kylart** [comment]
Solved in 2.0.0
