### ISSUE TITLE
Problem with search

### ISSUE THREAD

**Issue by Niandra8** [Kylart/Nyaapi#21]
Hi, is the repo still alive?

I was trying to use the search function on an electron app but apparently the promise is never fulfilled.

Coud you help with that?

**Comment by Kylart** [comment]
Can you share the code you are trying to run?

**Comment by Niandra8** [comment]
I managed to fix it by rewriting the search function to use fetch instead of request. For some reason I don't know, request doesn't seem to work on Electron for me.

Thanks!

**Comment by Kylart** [comment]
That's probably because you are trying to use it on the renderer when `request` cannot be imported unless you set `nodeIntegration` to true.
