### ISSUE TITLE
recaptcha for nyaa.si

### ISSUE THREAD

**Issue by jonese1234** [Kylart/Nyaapi#22]
hello,

when trying to upload there is now a recapture so it throws this error:

```
 statusCode: 400,
 error: '{"errors":{"recaptcha":["The response parameter is missing."]}}'
```

hopefully there is a way round it.

**Comment by Kylart** [comment]
Well, the fact that they added a captcha means that they don't want automated upload that don't come from their website. There are probably ways around it but I don't think it would be a good idea.

They might setup an API to allows external sources to upload to their db. I'll try asking them.

**Comment by jonese1234** [comment]
Seems like they have removed the Captcha.
So i think we are ok for now.

**Comment by jonese1234** [comment]
Actually looks like its based in the length of the account. So newly created ones will have Captchas
