### ISSUE TITLE
Feature/API URL Customization

### ISSUE THREAD

**Issue by guydht** [Kylart/Nyaapi#23]
Hey
I'd love this package to include the possibility to specify the base url for the apis.
For example. I want to stop using nyaa.si and instead use nyaa.iss.one
It could be as easy as:

`si.setBaseUrl('https://nyaa.iss.one')`

**Comment by Kylart** [comment]
Sorry for the very long answer.

You can now use the helper method to do exactly that in v2.4.0.

```javascript
const { si, pantsu } = require('nyaapi')

si.config.updateBaseUrl('https://nyaa.iss.one')

pantsu.config.updateBaseUrl('https://nyaa.pantsu.net')
```
