### ISSUE TITLE
Search: Nyaa returns 404 when search and page empty

### ISSUE THREAD

**Issue by cchudant** [Kylart/Nyaapi#4]
Hello (: 
I've recently found a bug in Nyaa that affects your code

The normal behaviour is: when you search with a keyword, i.e. "Youjo Senki" if your page number is too high (for exemple page 6 when the last page is 5), you get a normal response but without content.
https://nyaa.si/user/HorribleSubs?f=0&c=1_2&q=youjo%20senki&p=5
That's the default behaviour you use in your code.

But when you search without keyword, you get a nice 404 error : 
https://nyaa.si/user/HorribleSubs?f=0&c=1_2&q=&p=999

so obviously that messes up a lot of things... 
For example this code will reject with a 404 error:
```js
si.searchAllByUser('Refrain', null, { category: '1_3' })
```
`Error: Request failed with status code 404`

and the innerloop here ([search line 211](https://github.com/SkyBeastMC/Nyaapi/blob/master/src/si/search.js#L211)) will loop forever...

That's not your code's fault but I needed this particular case to work so I forked your repo, but as the bug is quite subtle and [the only workaround is kinda messy](https://github.com/SkyBeastMC/Nyaapi/commit/9a832dee404a8be08980cc2963dd1b0a01e8b147), I will not create a pull request
Instead [I opened up an Issue on the Nyaa repository](https://github.com/nyaadevs/nyaa/issues/482) but I doubt they will fix it

I might as well fix Nyaa myself but I don't have time :x

**Comment by cchudant** [comment]
ok i got instant closed on Nyaa xD

**Comment by Kylart** [comment]
Hello!

I kinda get your point and I thought up different fixes for your particular case. As I understand it, you want to get an empty array when you're searching for torrents made by one user but without any keyword.

```javascript
si.searchAllByUser('Refrain', null, { category: '1_3' })
```

This is definitely a particular case but I understand the need. Though, I don't really understand why you expect an empty array, I actually really like the default behavior of nyaa where if you do this: 
```javascript
si.searchAllByUser('Refrain', '*', { category: '1_3' })
```
you get all the results from the last available page. This actually makes more sense to me and is easy to implement from your end.

I'm sorry I don't have a really fix for your particular problem but I really think what I'm suggesting makes some sense. 

Doing
```javascript
if (!term && err.response.status === 404) resolve([])
```
seems really from my point of view as it could bring some nasty bugs.

As for nyaa.si, I know they currently have (had) some troubles to deal with and I feel like they don't really people scraping their websites for various reasons so they don't plan on supporting it obviously 😄
